//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urdu_Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_Submit_Info
    {
        public int Id { get; set; }
        public int Article_Id { get; set; }
        public int SubmittedForIssue { get; set; }
        public int In_Category { get; set; }
        public bool Available { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Issue Issue { get; set; }
        public virtual Magazine_Category Magazine_Category { get; set; }
    }
}
