//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urdu_Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Issue()
        {
            this.Article_Issue = new HashSet<Article_Issue>();
            this.Article_Submit_Info = new HashSet<Article_Submit_Info>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public int Magazine_Id { get; set; }
        public System.DateTime Issue_date { get; set; }
        public Nullable<System.DateTime> Submission_date { get; set; }
        public bool Status { get; set; }
        public bool isPublished { get; set; }
        public string Folder { get; set; }
        public string fileName { get; set; }
        public string Cover { get; set; }
        public Nullable<byte> pdfStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_Issue> Article_Issue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_Submit_Info> Article_Submit_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Magazine Magazine { get; set; }
    }
}
