//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urdu_Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public Nullable<int> who { get; set; }
        public Nullable<int> type { get; set; }
        public string description { get; set; }
        public string link { get; set; }
        public Nullable<int> issue_id { get; set; }
        public Nullable<int> article_id { get; set; }
        public Nullable<int> mag_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual User User { get; set; }
    }
}
