//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urdu_Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadMedia
    {
        public int Id { get; set; }
        public string imgPath { get; set; }
        public string imgName { get; set; }
        public int userId { get; set; }
        public string imgFileName { get; set; }
    
        public virtual User User { get; set; }
    }
}
